### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by jayrat** [HoangNguyen17193/vscode-simple-rest-client#15]
When trying to use with a route that uses  https getting the following response

The response works with POSTMAN and the site opens in browsers fine and shows no errors with any of the certificates.

```
{
    "name": "RequestError",
    "message": "Error: unable to verify the first certificate",
    "cause": {
        "code": "UNABLE_TO_VERIFY_LEAF_SIGNATURE"
    },
    "error": {
        "code": "UNABLE_TO_VERIFY_LEAF_SIGNATURE"
    },
    "options": {
        "method": "POST",
        "uri": "https://<BLANKED>",
        "body": "{\"username\":\"<BLANKED>\",\"password\":\"<BLANKED>\"}",
        "headers": {
            "Content-Type": "application/json"
        },
        "simple": true,
        "resolveWithFullResponse": false,
        "transform2xxOnly": false
    }
}
```

**Comment by HoangNguyen17193** [comment]
@jayrat I will add 2 options: rejectUnauthorized, insecure in next version. Hope that works for you
https://github.com/request/request-promise/issues/225

**Comment by HoangNguyen17193** [comment]
@jayrat  I added request options, pls try on new vesion
<img width="530" alt="Screen Shot 2020-04-08 at 10 47 21" src="https://user-images.githubusercontent.com/16357791/78742910-5f9ea600-7987-11ea-9f16-532eae74747c.png">
