### ISSUE TITLE
[Ubuntu] Panel empty, command does not exist

### ISSUE THREAD

**Issue by marcobuschini** [HoangNguyen17193/vscode-simple-rest-client#21]
The side panel from where I am supposed to create a new request comes out empty. The command to execute a new request says that "command 'RestClient.newRequest' not found."

**Comment by HoangNguyen17193** [comment]
@marcobuschini
Pls re-install and give me some screen shots, I can't reproduce this issue

**Comment by marcobuschini** [comment]
@HoangNguyen17193 the link below shows the screenshot. I hope it helps.

![image](https://user-images.githubusercontent.com/6851947/83407293-b6b57a00-a410-11ea-8b7c-dab990fb5184.png)

**Comment by HoangNguyen17193** [comment]
Maybe it's an issue on Ubuntu OS, I have tested on Mac and window. 
<img width="1397" alt="Screen Shot 2020-06-04 at 14 19 50" src="https://user-images.githubusercontent.com/16357791/83727586-828bc480-a66f-11ea-8f7c-4d3227b44f81.png">

**Comment by HoangNguyen17193** [comment]
Have u tried to run vscode app with sudo?

**Comment by marcobuschini** [comment]
Are you serious? I will never run a user space app as root.

Il giorno gio 4 giu 2020 alle ore 09:32 Hoang Nguyen (Tino) <
notifications@github.com> ha scritto:

**Comment by HoangNguyen17193** [comment]
@marcobuschini I mean you can try 1 time to find the issue. Can you give me the extension version?

**Comment by marcobuschini** [comment]
Root privileges are not required to save files on the user's home dir. Therefore that is not the issue. The extension version is 1.3.0.

**Comment by HoangNguyen17193** [comment]
sr @marcobuschini , I don't have Ubuntu device for testing.

**Comment by marcobuschini** [comment]
Seeking for alternatives then.

**Comment by HoangNguyen17193** [comment]
T.T

**Comment by HoangNguyen17193** [comment]
"Hi there,
I am a Linux user, so not a developer.
I confirm extension does not work on Ubuntu. However I have found a solution:

After installing the extension, go to the extension folder:
~/.vscode/extensions/extension-name-1.0.5 (for Visual Studio Code)
~/.vscode-oss/extensions/extension-name-1.0.5 (for VSCodium)

and run:
npm install

npm run compile

npm run lint (optional, I think)

Be sure to have node installed and to restart vscode or reload you vscode window."

@marcobuschini Please try this solution I found on some repositories

**Comment by marcobuschini** [comment]
Doesn't work:

```
marcobuschini@invernomuto:~/.vscode/extensions/tino.simple-rest-client-1.3.0 $ npm run compile

> simple-rest-client@1.3.0 compile /home/marcobuschini/.vscode/extensions/tino.simple-rest-client-1.3.0
> tsc -p ./

error TS5057: Cannot find a tsconfig.json file at the specified directory: './'.
```

**Comment by HoangNguyen17193** [comment]
@marcobuschini can u give me the list of filenames on this directory?

**Comment by marcobuschini** [comment]
```
$ ls .vscode/extensions/tino.simple-rest-client-1.3.0/ -1
CHANGELOG.md
design
LICENSE.txt
node_modules
out
package.json
package-lock.json
README.md
resources

```

**Comment by HoangNguyen17193** [comment]
https://github.com/HoangNguyen17193/vscode-simple-rest-client/blob/master/tsconfig.json 
You can try with this file. @marcobuschini

**Comment by marcobuschini** [comment]
@HoangNguyen17193 where do I have to put that file? In the package install directory? Or will I have to rebuild the package myself?

**Comment by HoangNguyen17193** [comment]
@marcobuschini Follow the comment previously, you should put that file in the package install directory and run `npm run compile`.
VSCode extensions do not work well on Linux/Ubuntu. Rebuild package is a temporary solution. I'm looking for solutions
