### ISSUE TITLE
v1.4.1 doesn't handle error responses (e.g. 404)

### ISSUE THREAD

**Issue by robgilliam** [HoangNguyen17193/vscode-simple-rest-client#28]
In version 1.4.1, if the API returns an error response (e.g. 404), then nothing happens on-screen.

VS Code console log attached

[Simple-Rest-Client.log](https://github.com/HoangNguyen17193/vscode-simple-rest-client/files/5446867/Simple-Rest-Client.log)

Changing the server under test to simply return a 200 status for the exact same response shows the response in Simple Rest Client (as expected)

Downgrading to version 1.3.1 also works as expected.

**Comment by HoangNguyen17193** [comment]
@robgilliam Thanks for reporting this issue. Please try the new version 1.4.2
